version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MONGO_URI=mongodb://mongodb-myapp:27017/
    ports:
      - 3000:3000
    depends_on:
      - mongodb-myapp
      - redis-myapp
    command: npm run start:dev
    env_file:
    - .env
    volumes:
     - .:/usr/src/app
     - /usr/src/app/node_modules
    restart: unless-stopped
  mongodb-myapp:
      image : mongo
      container_name: mongodb-myapp
      volumes:
        - ./database:/data/db
      ports:
        - 27017:27017
      restart: always
  redis-myapp:
    image: 'redis:alpine'
    volumes:
      - ./redis:/data
    ports:
      - 6379:6379